# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: hello-world-nodejs # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs10.x
  profile: serverless-admin
  stage: tst
  region: us-east-1
  memorySize: 128
  timeout: 3
# you can define service wide environment variables here
  environment:
    variable1: value1
    variable2: value2
    FIRST_NAME: "Carolina"
  vpc:
    securityGroupIds:
      - sg-009b1f65acdf9457c
    subnetIds: 
      - subnet-ff5101a3
      - subnet-a8f3a7cf


# you can add packaging information here
package:
  individually: true
  excludeDevDependencies: true


functions:
  hello-short-timeout:
    handler: handler.handler
    package:
      individually: true
      exclude:
        - node_modules/**
  hello-long-timeout:
    handler: handler.handler
    memorySize: 256
    timeout: 6
    package:
      individually: true
      exclude:
        - node_modules/**
  hello-iam-example:
    handler: handler-iam.handler
  handler-envirionment-variables-carolina:
    handler: handler-envirionment-variables.handler
    package:
      individually: true
      exclude:
        - node_modules/**
  handler-envirionment-variables-camila:
    handler: handler-envirionment-variables.handler
    environment:
      FIRST_NAME: "Camila"
    package:
      individually: true
      exclude:
        - node_modules/**
